import os
import re

files_to_update = [
    r'd:\yukti\frontend\app\settings\page.tsx',
    r'd:\yukti\frontend\app\score\[categoryId]\page.tsx',
    r'd:\yukti\frontend\app\financials\page.tsx',
    r'd:\yukti\frontend\app\error.tsx',
    r'd:\yukti\frontend\app\category\[categoryId]\page.tsx',
    r'd:\yukti\frontend\app\capital\page.tsx'
]

replacements = {
    r'\bbg-black\b': 'bg-warm-bg',
    r'\bbg-zinc-900\b': 'bg-warm-surface',
    r'\bbg-zinc-800\b': 'bg-warm-surface',
    r'\bborder-zinc-800\b': 'border-warm-border',
    r'\bborder-zinc-700\b': 'border-warm-border',
    r'\bborder-zinc-600\b': 'border-warm-muted',
    r'\btext-zinc-500\b': 'text-warm-muted',
    r'\btext-zinc-400\b': 'text-warm-muted',
    r'\btext-zinc-300\b': 'text-warm-text',
    r'\btext-white\b': 'text-warm-text',
    r'\btext-terminal-text\b': 'text-warm-text',
    r'\btext-terminal-cyan\b': 'text-warm-primary',
    r'\btext-terminal-green\b': 'text-warm-secondary',
    r'\btext-terminal-amber\b': 'text-orange-500',
    r'\btext-terminal-red\b': 'text-red-600',
    r'\bborder-terminal-cyan\b': 'border-warm-primary',
    r'\bborder-terminal-green\b': 'border-warm-secondary',
    r'\bborder-terminal-amber\b': 'border-orange-500',
    r'\bbg-terminal-cyan/20\b': 'bg-warm-primary/20',
    r'\bbg-terminal-green/20\b': 'bg-warm-secondary/20',
    r'\bfont-mono\b': 'font-sans',
    r'\buppercase tracking-widest\b': ''
}

for path in files_to_update:
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        for pattern, replacement in replacements.items():
            content = re.sub(pattern, replacement, content)
            
        # Clean up any double spaces generated by removing strings
        content = re.sub(r' +', ' ', content)
        content = content.replace('className=\" ', 'className=\"').replace(' \"', '\"')
            
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {path}")
    else:
        print(f"File not found: {path}")
