import os
from pathlib import Path

base_dir = Path(r"d:\yukti")

dirs = [
    "backend/alembic/versions",
    "backend/app/core",
    "backend/app/models",
    "backend/app/schemas",
    "backend/app/api",
    "backend/app/engines/market_intelligence",
    "backend/app/data_layer/datasets/location_1_solapur",
    "backend/app/data_layer/datasets/location_2_sparse",
    "backend/app/data_layer/datasets/schemes",
    "backend/app/ai_layer",
    "backend/app/report/templates",
    "backend/app/services",
    "backend/tests",
    "frontend/app/profile",
    "frontend/app/capital",
    "frontend/app/fork",
    "frontend/app/results",
    "frontend/app/category/[id]",
    "frontend/app/financial-structuring",
    "frontend/app/scheme-match",
    "frontend/app/emi",
    "frontend/app/simulator",
    "frontend/app/score",
    "frontend/app/next-steps",
    "frontend/app/report",
    "frontend/components",
    "frontend/lib",
    "frontend/public",
    "data/sources",
    "docs",
]

files = [
    "README.md",
    ".env.example",
    "docker-compose.yml",
    "backend/pyproject.toml",
    "backend/requirements.txt",
    "backend/app/main.py",
    "backend/app/core/config.py",
    "backend/app/core/db.py",
    "backend/app/models/user.py",
    "backend/app/models/location.py",
    "backend/app/models/business_category.py",
    "backend/app/models/session.py",
    "backend/app/models/competitor.py",
    "backend/app/models/market_metric.py",
    "backend/app/models/cost_model.py",
    "backend/app/models/government_scheme.py",
    "backend/app/models/scheme_rule.py",
    "backend/app/models/loan_product.py",
    "backend/app/models/financial_projection.py",
    "backend/app/models/scenario.py",
    "backend/app/models/recommendation.py",
    "backend/app/models/confidence_tag.py",
    "backend/app/models/source.py",
    "backend/app/schemas/profile.py",
    "backend/app/schemas/ranking.py",
    "backend/app/schemas/market.py",
    "backend/app/schemas/finance.py",
    "backend/app/schemas/scheme.py",
    "backend/app/schemas/simulation.py",
    "backend/app/schemas/recommendation.py",
    "backend/app/schemas/report.py",
    "backend/app/api/routes_profile.py",
    "backend/app/api/routes_rank.py",
    "backend/app/api/routes_market.py",
    "backend/app/api/routes_finance.py",
    "backend/app/api/routes_schemes.py",
    "backend/app/api/routes_simulate.py",
    "backend/app/api/routes_recommend.py",
    "backend/app/api/routes_explain.py",
    "backend/app/api/routes_report.py",
    "backend/app/engines/location_service.py",
    "backend/app/engines/market_intelligence/market_reach.py",
    "backend/app/engines/market_intelligence/opportunity_gaps.py",
    "backend/app/engines/market_intelligence/swot.py",
    "backend/app/engines/market_intelligence/threats.py",
    "backend/app/engines/market_intelligence/competitor_density.py",
    "backend/app/engines/market_intelligence/pricing.py",
    "backend/app/engines/financial_engine.py",
    "backend/app/engines/scheme_engine.py",
    "backend/app/engines/recommendation_engine.py",
    "backend/app/engines/simulation_engine.py",
    "backend/app/data_layer/retrieval.py",
    "backend/app/data_layer/confidence_tagging.py",
    "backend/app/data_layer/datasets/location_1_solapur/demographics.json",
    "backend/app/data_layer/datasets/location_1_solapur/competitors.json",
    "backend/app/data_layer/datasets/location_1_solapur/pricing.json",
    "backend/app/data_layer/datasets/location_1_solapur/cost_profiles.json",
    "backend/app/data_layer/datasets/schemes/nsfdc_schemes.json",
    "backend/app/ai_layer/intent_classifier.py",
    "backend/app/ai_layer/context_builder.py",
    "backend/app/ai_layer/prompt_templates.py",
    "backend/app/ai_layer/llm_client.py",
    "backend/app/ai_layer/numeric_validator.py",
    "backend/app/report/report_builder.py",
    "backend/app/report/templates/report.html.jinja",
    "backend/app/report/pdf_export.py",
    "backend/app/services/ranking_service.py",
    "backend/app/services/session_service.py",
    "backend/tests/test_boundary_values.py",
    "backend/tests/test_scheme_engine.py",
    "backend/tests/test_financial_engine.py",
    "backend/tests/test_numeric_validator.py",
    "backend/tests/test_recommendation_engine.py",
    "frontend/package.json",
    "frontend/app/page.tsx",
    "frontend/app/profile/page.tsx",
    "frontend/app/capital/page.tsx",
    "frontend/app/fork/page.tsx",
    "frontend/app/results/page.tsx",
    "frontend/app/category/[id]/page.tsx",
    "frontend/app/financial-structuring/page.tsx",
    "frontend/app/scheme-match/page.tsx",
    "frontend/app/emi/page.tsx",
    "frontend/app/simulator/page.tsx",
    "frontend/app/score/page.tsx",
    "frontend/app/next-steps/page.tsx",
    "frontend/app/report/page.tsx",
    "frontend/components/ConfidenceBadge.tsx",
    "frontend/components/SourceTooltip.tsx",
    "frontend/components/VerdictBanner.tsx",
    "frontend/components/ScoreDial.tsx",
    "frontend/components/WhatIfSlider.tsx",
    "frontend/components/EMITable.tsx",
    "frontend/components/MapRadiusOverlay.tsx",
    "frontend/components/CopilotOverlay.tsx",
    "frontend/components/ProgressStepper.tsx",
    "frontend/lib/api-client.ts",
    "frontend/lib/formatters.ts",
    "docs/demo_script_3min.md",
    "docs/demo_script_5min.md",
    "docs/judge_qna_prep.md",
    "docs/data_provenance.md",
]

for d in dirs:
    (base_dir / d).mkdir(parents=True, exist_ok=True)

for f in files:
    (base_dir / f).touch(exist_ok=True)
