import json
import logging
from pathlib import Path
from fastapi import APIRouter
from typing import List, Dict, Optional

router = APIRouter()
logger = logging.getLogger(__name__)

# ── Static state/district lists ────────────────────────────────────────────
STATES = [
    {"id": "MH", "name": "Maharashtra"},
    {"id": "GJ", "name": "Gujarat"},
    {"id": "KA", "name": "Karnataka"}
]

DISTRICTS: Dict[str, List[Dict]] = {
    "MH": [
        {"id": "MH_SOL", "name": "Solapur"},
        {"id": "MH_PUN", "name": "Pune"},
        {"id": "MH_NSK", "name": "Nashik"}
    ],
    "GJ": [
        {"id": "GJ_AMD", "name": "Ahmedabad"},
        {"id": "GJ_SUR", "name": "Surat"}
    ],
    "KA": [
        {"id": "KA_BLR", "name": "Bangalore"},
        {"id": "KA_MYS", "name": "Mysore"}
    ]
}

# ── LGD village data (generated by scripts/extract_lgd_locations.py) ───────
_LOCATIONS_FILE = Path(__file__).resolve().parent.parent.parent / "data" / "processed" / "solapur_locations.json"
_CENSUS_FILE    = Path(__file__).resolve().parent.parent.parent / "data" / "processed" / "solapur_villages.json"

def _load_locations() -> dict:
    try:
        with open(_LOCATIONS_FILE, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.warning(f"solapur_locations.json not found: {e}")
        return {}

def _load_census() -> dict:
    try:
        with open(_CENSUS_FILE, encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.warning(f"solapur_villages.json not found: {e}")
        return {}

_LOCATIONS = _load_locations()
_CENSUS    = _load_census()


# ── API Endpoints ───────────────────────────────────────────────────────────

@router.get("/states")
async def get_states() -> List[Dict[str, str]]:
    return STATES


@router.get("/districts")
async def get_districts(state_id: str) -> List[Dict[str, str]]:
    return DISTRICTS.get(state_id, [])


@router.get("/solapur/talukas")
async def get_solapur_talukas():
    """
    Returns all 11 Solapur talukas from LGD data.
    Source: Local Government Directory (eGov India).
    """
    talukas = _LOCATIONS.get("talukas", [])
    if not talukas:
        # Fallback hardcoded list
        return {"talukas": [
            "Akkalkot", "Barshi", "Karmala", "Madha", "Malshiras",
            "Mangalvedhe", "Mohol", "Pandharpur", "Sangole",
            "Solapur North", "Solapur South"
        ], "source": "hardcoded_fallback"}
    return {
        "talukas": [t["name"] if isinstance(t, dict) else t for t in talukas],
        "source": _LOCATIONS.get("_source", "LGD"),
        "total": len(talukas)
    }


@router.get("/solapur/villages")
async def get_solapur_villages(taluka: Optional[str] = None, search: Optional[str] = None):
    """
    Returns all Solapur villages from LGD data.
    Optionally filter by taluka name or search string.
    Source: Local Government Directory (eGov India) — 1,154 villages.
    """
    villages = _LOCATIONS.get("villages", [])

    if taluka:
        villages = [v for v in villages if v.get("taluka", "").lower() == taluka.lower()]

    if search and len(search) >= 2:
        search_lower = search.lower()
        villages = [
            v for v in villages
            if search_lower in v.get("village", "").lower()
            or search_lower in v.get("village_local", "").lower()
        ]

    return {
        "villages": villages[:200],  # cap at 200 for performance
        "total": len(villages),
        "source": _LOCATIONS.get("_source", "LGD"),
        "filtered_by_taluka": taluka,
        "filtered_by_search": search
    }


@router.get("/solapur/village-detail")
async def get_village_detail(name: str):
    """
    Returns Census 2011 population + household data for a specific Solapur village.
    Source: Census of India 2011 — Primary Census Abstract.
    """
    census_villages = _CENSUS.get("villages", {})
    key = name.lower().strip()

    # Exact match
    rec = census_villages.get(key)

    # Partial match
    if not rec:
        for k, v in census_villages.items():
            if key in k or k in key:
                rec = v
                break

    if not rec:
        return {
            "found": False,
            "name": name,
            "message": "Village not found in Census 2011 data",
            "data_source": "Census 2011 (Solapur)"
        }

    pop_2011 = rec.get("population_2011", 0)
    hh_2011  = rec.get("households_2011", 0)
    pop_2026 = round(pop_2011 * 1.196)  # ~1.2% annual growth, 15 years

    return {
        "found": True,
        "name": rec.get("name", name),
        "subdistrict": rec.get("subdistrict", ""),
        "population_2011": pop_2011,
        "households_2011": hh_2011,
        "population_2026_estimate": pop_2026,
        "sex_ratio": rec.get("sex_ratio", 0),
        "data_source": "Census of India 2011 — Primary Census Abstract",
        "confidence": "Medium",
        "note": "Population grown at 1.2%/yr from 2011 baseline for 2026 estimate"
    }


@router.get("/solapur/coverage")
async def get_coverage_info():
    """Returns metadata about YuktiFi's Solapur coverage."""
    total_villages = _LOCATIONS.get("total_villages", 0)
    census_count   = len(_CENSUS.get("villages", {}))
    talukas        = _LOCATIONS.get("talukas", [])

    return {
        "district": "Solapur",
        "state": "Maharashtra",
        "total_villages_lgd": total_villages,
        "total_villages_census": census_count,
        "talukas": [t["name"] if isinstance(t, dict) else t for t in talukas],
        "data_sources": [
            {"name": "LGD Village List", "source": "eGov India LGD", "coverage": "1,154 villages"},
            {"name": "Census 2011 Population", "source": "Census of India", "coverage": f"{census_count} villages"},
            {"name": "Purchasing Power", "source": "HCES 2022-23 (MOSPI)", "coverage": "11 talukas"},
            {"name": "WorldPop Grid", "source": "WorldPop 2025", "coverage": "All India 1km"},
            {"name": "Live Competitors", "source": "OpenStreetMap Overpass", "coverage": "5km radius"},
        ]
    }
